# twig:
#     file_name_pattern: '*.twig'

# when@test:
#     twig:
#         strict_variables: true
# twig:
#     file_name_pattern: '*.twig'
#     form_themes: ['form.theme.html.twig']
#     paths:
#         '%kernel.project_dir%/templates': ~
        
# when@test:
#     twig:
#         strict_variables: true


twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'form.theme.html.twig'
        - 'search.form.theme.html.twig'
    paths:
        '%kernel.project_dir%/templates': ~

when@test:
    twig:
        strict_variables: true
